### PR TITLE
Add Istio ingress/egress

### LINKED ISSUE #403: Can't enable/disable ingress and egress (Istio)
The `gatewayInstallOptions` is never set in the `helmChartParams`, so by default when installing Istio, ingress/egress gateway does not get installed (not sure if this is by design or not).

### PR DESCRIPTION
**Pull request by peterj**
This PR adds Istio ingress and egress options to the  CLI.

Closes #403
BOT NOTES: 
resolves https://github.com/solo-io/supergloo/issues/403

### CODE REVIEW

**Comment by ilackarms** [comment]
@peterj sorry, last annoying piece: you  need to generate using `protoc` version 3.6.1 for our CI to pass.
any difference in the generated files causes it to error, and that's the version we (unofficially) have pinned. we should update the doc for that

**Comment by EItanya** [comment]
Hello @peterj thanks for the PR!
A couple quick things to get the CI passing.

1) move the changelog file to a new directory `v0.3.15` because we release `v0.3.14` yesterday afternoon.
2) run `make update-deps` locally before running `make generated-code` and that should fix the diffs in the code-generation

**Comment by ilackarms** [comment]
@christian-posta

**Pull request merged**
