### PR TITLE
Fix links to installation instructions and developers.md

### PR DESCRIPTION
**Pull request by antweiss**
Signed-off-by: Anton Weiss <anton@otomato.link>
BOT NOTES: 
resolves https://github.com/solo-io/supergloo/issues/496

### CODE REVIEW

**Comment by ilackarms** [comment]
@antweiss looks like `/skip-ci` check isnt working, so we will have to wait for this to run through CI. thanks for the contribution!

**Comment by antweiss** [comment]
thanks @ilackarms 
looks like it's failing to find an EKS cluster.
who can help with fixing this?

**Pull request merged**
